DateTime parse for command parameters.
openmod/openmod pull request #280
Opened 2020-12-06 21:53 UTC by cemahseri

2020-12-06 21:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmod/openmod?pullRequest=280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmod/openmod?pullRequest=280) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmod/openmod?pullRequest=280) it.</sub>

2020-12-06 22:01 UTC, Trojaner commented
Thank you for your contributions.

There is one problem with the current parsing. It ignores the current culture. It should parse based on server's current culture and then fall back to various other formats. For example, in some countries you might specify date as mm/dd/yyyy or yyyy-mm-dd.

Also support for https://github.com/ti-ka/human-date-parser should be included. You should be able to enter dates as e.g. "1 week later" or "tomorrow" too.

2020-12-06 22:02 UTC, Trojaner requested changes
Thank you for your contributions.

There is one problem with the current parsing. It ignores the current culture. It should parse based on server's current culture and then fall back to various other formats. For example, in some countries you might specify date as mm/dd/yyyy or yyyy-mm-dd.

Also support for https://github.com/ti-ka/human-date-parser should be included. You should be able to enter dates as e.g. "1 week later" or "tomorrow" too.

2020-12-07 08:16 UTC, cemahseri commented
Parsing human readable dates makes total sense. I should have thought that. But I didn't quite get the parsing according to the server's current culture. Like, won't be setting an standart format would good?

2021-01-20 17:40 UTC, closed without merging