Fix vehicle lock pick
openmod/openmod pull request #365
Opened 2021-02-02 20:06 UTC by rube200

2021-02-02 20:10 UTC, Trojaner requested changes

2021-02-02 20:10 UTC, Trojaner commented on unturned/OpenMod.Unturned/Vehicles/Events/VehicleEventsListener.cs
> +                if (nativePlayer is null)
Please use == null instead so it checks if Unity has disposed / destroyed it

2021-02-02 20:10 UTC, Trojaner commented on unturned/OpenMod.Unturned/Vehicles/Events/VehicleEventsListener.cs
> +                if (player is null)
== null instead

2021-02-02 20:10 UTC, Trojaner commented on unturned/OpenMod.Unturned/Vehicles/Events/VehicleEventsListener.cs
> -                if (vehicle == null)
== null instead

2021-02-02 23:31 UTC, IAmSilK commented
@rube200 could you also change `IsCancelled = allow` to `IsCancelled = !allow`. This is a bug as well.

2021-02-03 00:11 UTC, Trojaner approved these changes

2021-02-03 00:56 UTC, rube200 commented on unturned/OpenMod.Unturned/Vehicles/Events/VehicleEventsListener.cs
> +                IsCancelled = !allow
@IAmSilK here

2021-02-03 00:56 UTC, rube200 commented
@IAmSilK That was the hole  point of doing this changes/PR

2021-02-03 01:46 UTC, merged