Fix for plugins' packages file not updating packages
openmod/openmod pull request #513
Opened 2021-05-22 22:55 UTC by IAmSilK

2021-05-22 23:09 UTC, Trojaner commented on framework/OpenMod.Core/Plugins/PluginAssemblyStore.cs
> +                        m_Logger.LogDebug(loaderException, "Exception occurred when getting types in plugin assembly");
Please log assembly name as well

2021-05-22 23:18 UTC, Trojaner requested changes
Must support `latest` as version in packages.yaml

2021-06-07 13:24 UTC, IAmSilK commented on framework/OpenMod.Core/Plugins/PluginAssemblyStore.cs
> +                        m_Logger.LogDebug(loaderException, "Exception occurred when getting types in plugin assembly");
Resolved by eee27bf

2022-07-25 15:31 UTC, rube200 commented
I tested with standalone and it seems to work fine.
packages.yaml
```
packages:
- id: OpenMod.Economy
  version: latest
```

2022-07-25 17:09 UTC, rube200 reviewed
Should be fixed now

2022-07-25 17:11 UTC, Trojaner approved these changes

2022-07-25 17:11 UTC, merged