Change OpenMod.EntityFrameworkCore to use Pomelo.EntityFrameworkCore.MySql
openmod/openmod pull request #525
Opened 2021-06-10 23:13 UTC by IAmSilK

Todo:
- [ ] Update UserDatabasePlugin to reflect changes and create new migrations
- [ ] Test new implementations work
- [ ] Changed OpenMod docs to reflect changes

2021-06-10 23:14 UTC, IAmSilK commented
#524

2021-06-13 19:46 UTC, Trojaner requested changes

2021-06-13 19:46 UTC, Trojaner commented on framework/OpenMod.EntityFrameworkCore.MySql/OpenModMySqlDbContext.cs
> +    /// public class MyDbContext : OpenModMySqlDbContext&lt;MyDbContext&gt;
Should stay as OpenModDbContext

2021-06-13 19:46 UTC, Trojaner commented on framework/OpenMod.EntityFrameworkCore.MySql/OpenModMySqlDbContext.cs
> +            optionsBuilder.UseMySql(connectionString,
This should be removed and done in a different way, e.g. in container/service configuration when you add the DbContext. DbContext itself should not care what the underlying provider is

2021-06-13 19:46 UTC, Trojaner commented
We can skip the UserDatabasePlugin for now, its not priority

2021-06-20 10:30 UTC, Trojaner approved these changes

2021-06-20 16:31 UTC, IAmSilK commented
Testing is finished

2021-06-21 07:02 UTC, merged