Feature/resources remove warnings costura fody
openmod/openmod pull request #680
Opened 2023-04-08 10:56 UTC by sunnamed434

Closes #676

2023-04-08 11:17 UTC, sunnamed434 commented on framework/OpenMod.Core/Helpers/AssemblyHelper.cs
> +            if (string.IsNullOrWhiteSpace(resourceName) == false)
Fixed

2023-04-08 11:17 UTC, sunnamed434 commented on framework/tests/OpenMod.Core.Tests/Helpers/AssemblyHelperTests.cs
> +            if (string.IsNullOrWhiteSpace(resourceName) == false)
Fixed

2023-04-08 11:17 UTC, sunnamed434 commented on framework/OpenMod.Core/Helpers/AssemblyHelper.cs
> +            }
Fixed

2023-04-08 11:17 UTC, sunnamed434 commented on framework/tests/OpenMod.Core.Tests/Helpers/AssemblyHelperTests.cs
> +            }
Fixed

2023-04-08 11:19 UTC, sunnamed434 commented on framework/OpenMod.Core/Helpers/AssemblyHelper.cs
> +            }
Fixed

2023-04-08 11:29 UTC, CyberAndrii requested changes
I don't really like the idea of supporting a specific library. Instead it would be better to have interface `IOpenModResourceFilter` with method like `bool IsOpenModResource(string name)` that will be called via reflection (same way as `IServiceConfigurator`). In an implementation of that interface plugin devs will be able to specify what files they want to extract (e.g. configs) and which not. Default to extract all if no implementation is found in the assembly.

2023-04-08 11:44 UTC, sunnamed434 commented
> I don't really like the idea of supporting a specific library. Instead it would be better to have interface `IOpenModResourceFilter` with method like `bool IsOpenModResource(string name)` that will be called via reflection (same way as `IServiceConfigurator`). In an implementation of that interface plugin devs will be able to specify what files they want to extract (e.g. configs) and which not. Default to extract all if no implementation is found in the assembly.

Definitely cool idea

2023-04-12 13:09 UTC, Trojaner commented
I agree with @CyberAndrii, closing for now

2023-04-12 13:09 UTC, closed without merging