Add Level events
openmod/openmod pull request #691
Opened 2023-04-11 18:09 UTC by Pandetthe

2023-04-11 18:22 UTC, Pandetthe commented
Added

2023-04-11 18:28 UTC, rube200 commented
The point wasnt to remove all the events.
More like
UnturnedPreLevelEvent : UnturnedLevelEvent : Event

2023-04-11 18:36 UTC, Pandetthe commented
I have skipped Level.onLevelExited, I don't know if it's called serverside

2023-04-12 02:14 UTC, DiFFoZ requested changes

2023-04-12 02:14 UTC, DiFFoZ commented on unturned/OpenMod.Unturned/Level/Events/LevelEventsListener.cs
> +            SDG.Unturned.Level.onLevelsRefreshed += OnLevelsRefreshed;
Remove it, it's not used on server-side

2023-04-12 02:14 UTC, DiFFoZ commented on unturned/OpenMod.Unturned/Level/Events/LevelEventsListener.cs
> +            SDG.Unturned.Level.onLevelsRefreshed -= OnLevelsRefreshed;
Remove it, it's not used on server-side

2023-04-12 02:14 UTC, DiFFoZ commented on unturned/OpenMod.Unturned/Level/Events/UnturnedLevelEvent.cs
Do we really need to pass the scene index? I think we only need `Level.BUILD_INDEX_GAME` and everything else should be skipped.

2023-04-12 06:36 UTC, Pandetthe commented on unturned/OpenMod.Unturned/Level/Events/UnturnedLevelEvent.cs
Not really

2023-04-12 13:33 UTC, DiFFoZ approved these changes

2023-04-12 13:36 UTC, merged