netstandard2.1 support
openmod/openmod pull request #737
Opened 2023-08-17 10:28 UTC by DiFFoZ

- Added `netstandard2.1` to target framework.
- Removed unused Fody weavers.
- Fixed some Fody warnings.
- Fixed GitHub source link duplicate package warnings.

2023-09-05 18:33 UTC, CyberAndrii requested changes

2023-09-05 18:33 UTC, CyberAndrii commented on standalone/OpenMod.Standalone/OpenMod.Standalone.csproj
> +    <TargetFrameworks>net7.0</TargetFrameworks>
Also https://github.com/openmod/openmod/blob/main/.github/workflows/OpenMod.Standalone.yaml#L46..L71

2023-09-22 13:59 UTC, CyberAndrii requested changes
Sorry, this didn't come to my mind earlier, but we still need to figure out https://github.com/openmod/openmod/issues/718 before this PR can be merged. That's because it will no longer be possible to install .NET Framework libraries if we ship OpenMod.NuGet targeting .NET Standard.

Alternatively, we could make both OpenMod.NuGet and the Module target net481 (or whatever version Unturned is going to use) like it is right now with net461.

2023-09-22 15:52 UTC, DiFFoZ commented
What about of implementing a method for NuGet manager, e.g:
```cs
public void IncludeAvailableFrameworks(params NuGetFramework[] frameworks)
```

And then module should call it to add the range of supported frameworks.
Unturned:
```
IncludeAvailableFrameworks(net461-net481)
```
Standalone:
```
IncludeAvailableFrameworks(net6.0-net7.0)
```

2023-09-24 17:19 UTC, DiFFoZ commented
I have got implemented it in https://github.com/openmod/openmod/pull/737/commits/1ac3bc925ca8f40dc7a759da6cf7c67bf48ad211.

If `OpenMod.NuGet` was downloaded with version `.netstandard2.1`, then it will check for if it's running under Mono, and if it does, then adds `.net4.8.0` to the supported framework.

If a version is not `.netstandard2.1` or is not running under Mono, then it will only use the target framework version of `OpenMod.Nuget`. And for that I have added `.net4.8.0` to the supported framework.

2023-09-27 09:48 UTC, DiFFoZ commented
Updated some packages with major changes, should be not cause any breaking changes.
https://autofac.readthedocs.io/en/latest/whats-new/upgradingfrom6to7.html
https://github.com/serilog/serilog/releases/tag/v3.0.0
https://github.com/andrewlock/NetEscapades.Configuration/issues/75#issuecomment-1469506349 (minor breaking change due to using reflection)

But some of them created breaking change by pinning the version of `Microsoft.*` package to v6 or v7, we are still using v3. So these are not updated to the major version.
https://github.com/serilog/serilog-extensions-hosting/releases/tag/v7.0.0
https://github.com/autofac/Autofac.Extensions.DependencyInjection/releases/tag/v8.0.0

2023-10-13 18:37 UTC, merged